drop table product if exists;

create table product (
    id bigint generated by default as identity (start with 1),
    description varchar(1000),
    name varchar(255),
    photo varchar(255),
    price double,
    primary key (id)
);