INSERT INTO Product (id,name,description,photo,price) VALUES
(1,'Chester','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac ante vel ante malesuada gravida id at odio. Vivamus massa mi, rhoncus ac enim ut, cursus egestas justo. Vestibulum id finibus diam, non hendrerit mauris. Donec at libero eu arcu fermentum viverra ut scelerisque est. Morbi molestie egestas laoreet. Aliquam gravida ex at scelerisque pulvinar. Mauris quam elit, fermentum eu eleifend nec, suscipit a dui. Aenean cursus non justo maximus ultrices. Vestibulum sit amet ligula velit. Suspendisse non justo diam. Nullam lacinia ex nisl, a venenatis orci feugiat ut. Sed maximus turpis et condimentum consectetur. Aenean non eros tincidunt, pulvinar felis vel, viverra turpis.','/uploads/monitor.png',9285.99),
(2,'Linus','egestas. Aliquam fringilla cursus purus. Nullam scelerisque','/uploads/laptop.jpg',5496),
(3,'Aquila','amet metus. Aliquam erat volutpat. Nulla facilisis.','/uploads/monitor.png',1838),
(4,'Bruno','vitae dolor. Donec fringilla. Donec feugiat metus sit','/uploads/laptop.jpg',2519),
(5,'Brenden','Suspendisse tristique neque venenatis lacus.','/uploads/monitor.png',7663),
(6,'Vernon','orci.','/uploads/laptop.jpg',8357),
(7,'Cooper','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum','/uploads/monitor.png',7594),
(8,'Phillip','nunc sed libero. Proin sed turpis','/uploads/laptop.jpg',7068),
(9,'Noah','Suspendisse','/uploads/laptop.jpg',6070),
(10,'Ross','tortor, dictum','/uploads/laptop.jpg',460),
(11,'Porter','nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus','/uploads/laptop.jpg',6154),
(12,'Adrian','nec, diam. Duis','/uploads/laptop.jpg',9689),
(13,'Wesley','varius et, euismod et,','/uploads/laptop.jpg',308),
(14,'Lance','semper rutrum. Fusce dolor quam, elementum','/uploads/laptop.jpg',7806),
(15,'Andrew','tellus non magna. Nam ligula elit, pretium et,','/uploads/laptop.jpg',2628),
(16,'Bernard','arcu. Vestibulum ut eros non enim commodo','/uploads/laptop.jpg',5102),
(17,'Hilel','purus gravida','/uploads/laptop.jpg',7493),
(18,'Lamar','nisi. Aenean eget metus. In','/uploads/laptop.jpg',9855),
(19,'Lev','semper et, lacinia vitae, sodales at, velit.','/uploads/laptop.jpg',7625),
(20,'Lamar','Duis elementum, dui quis accumsan convallis, ante lectus convallis est,','/uploads/laptop.jpg',3496),
(21,'Tarik','sociis natoque penatibus et magnis dis parturient','/uploads/laptop.jpg',989),
(22,'Amery','Cras eget nisi dictum augue malesuada malesuada. Integer id magna','/uploads/laptop.jpg',5688),
(23,'Reese','sed','/uploads/laptop.jpg',4497),
(24,'Kelly','est tempor bibendum.','/uploads/laptop.jpg',2429),
(25,'Phelan','diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus','/uploads/laptop.jpg',2430),
(26,'Rigel','Sed','/uploads/laptop.jpg',9888),
(27,'Tucker','luctus aliquet odio.','/uploads/laptop.jpg',1351),
(28,'Dominic','ipsum ac mi eleifend','/uploads/laptop.jpg',1677),
(29,'Scott','sem semper erat, in consectetuer ipsum nunc id enim. Curabitur','/uploads/laptop.jpg',8096),
(30,'Stuart','posuere cubilia Curae; Phasellus ornare.','/uploads/laptop.jpg',7466),
(31,'Dorian','tempor, est ac mattis','/uploads/laptop.jpg',7010),
(32,'Noah','bibendum','/uploads/laptop.jpg',3396),
(33,'Kenyon','interdum. Sed auctor odio a purus. Duis elementum,','/uploads/laptop.jpg',1220),
(34,'Wayne','augue','/uploads/laptop.jpg',2799),
(35,'Dolan','enim. Curabitur massa. Vestibulum','/uploads/laptop.jpg',7816),
(36,'Dominic','senectus et netus et malesuada fames ac turpis egestas.','/uploads/laptop.jpg',2546),
(37,'Otto','velit. Cras lorem lorem, luctus ut, pellentesque','/uploads/laptop.jpg',1633),
(38,'Marvin','leo elementum sem, vitae aliquam eros turpis non','/uploads/laptop.jpg',378),
(39,'Baker','quam, elementum at, egestas a, scelerisque sed, sapien. Nunc','/uploads/laptop.jpg',4709),
(40,'Adrian','sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed','/uploads/laptop.jpg',2552),
(41,'Reed','elementum sem, vitae aliquam eros turpis non enim.','/uploads/laptop.jpg',3858),
(42,'Erich','vel lectus. Cum','/uploads/laptop.jpg',8466),
(43,'Nash','parturient','/uploads/laptop.jpg',385),
(44,'Tanek','ac mattis semper, dui lectus rutrum urna, nec luctus felis','/uploads/laptop.jpg',3715),
(45,'Maxwell','vel arcu. Curabitur ut odio','/uploads/laptop.jpg',9681),
(46,'Avram','rutrum lorem ac risus. Morbi metus. Vivamus euismod','/uploads/laptop.jpg',5032),
(47,'Daniel','Aliquam','/uploads/laptop.jpg',2852),
(48,'Hu','mollis','/uploads/laptop.jpg',9767),
(49,'Julian','faucibus orci luctus et ultrices','/uploads/laptop.jpg',3753),
(50,'Herman','Duis risus','/uploads/laptop.jpg',3815),
(51,'Lane','et, commodo at,','/uploads/laptop.jpg',1915),
(52,'Barclay','dis parturient montes, nascetur ridiculus mus. Proin vel nisl.','/uploads/laptop.jpg',8076),
(53,'Yardley','Nullam feugiat placerat velit. Quisque','/uploads/laptop.jpg',13),
(54,'Gregory','eget nisi dictum augue malesuada malesuada. Integer id magna et','/uploads/laptop.jpg',5431),
(55,'Addison','Vivamus rhoncus. Donec est. Nunc','/uploads/laptop.jpg',3663),
(56,'Wesley','Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing','/uploads/laptop.jpg',4672),
(57,'Garrison','arcu. Morbi sit amet massa. Quisque porttitor','/uploads/laptop.jpg',3790),
(58,'Alec','condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing','/uploads/laptop.jpg',7999),
(59,'Noah','ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis.','/uploads/laptop.jpg',6570),
(60,'Austin','ornare. In faucibus. Morbi vehicula. Pellentesque','/uploads/laptop.jpg',2726),
(61,'Phelan','eget nisi dictum augue malesuada malesuada. Integer id','/uploads/laptop.jpg',515),
(62,'Wallace','lacinia at, iaculis','/uploads/laptop.jpg',3147),
(63,'Phillip','egestas. Fusce aliquet magna','/uploads/laptop.jpg',6740),
(64,'Elijah','amet','/uploads/laptop.jpg',9344),
(65,'Rogan','Maecenas ornare egestas ligula.','/uploads/laptop.jpg',4062),
(66,'Eric','tellus','/uploads/laptop.jpg',1926),
(67,'Lyle','sem magna nec quam. Curabitur','/uploads/laptop.jpg',9433),
(68,'Abraham','Aenean euismod mauris eu elit. Nulla','/uploads/laptop.jpg',4374),
(69,'Lionel','elit. Curabitur','/uploads/laptop.jpg',9747),
(70,'Flynn','mattis semper, dui lectus rutrum urna, nec luctus','/uploads/laptop.jpg',1010),
(71,'Henry','augue, eu tempor erat neque non quam.','/uploads/laptop.jpg',756),
(72,'Dexter','magna a neque. Nullam ut nisi a odio semper','/uploads/laptop.jpg',2091),
(73,'Elliott','lorem, sit','/uploads/laptop.jpg',4846),
(74,'Hayes','Sed eget lacus.','/uploads/laptop.jpg',235),
(75,'Hashim','Nullam ut nisi','/uploads/laptop.jpg',4872),
(76,'Norman','imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque','/uploads/laptop.jpg',8112),
(77,'Lucian','Phasellus fermentum','/uploads/laptop.jpg',3693),
(78,'Ray','Ut sagittis lobortis mauris. Suspendisse aliquet molestie','/uploads/laptop.jpg',9618),
(79,'Dalton','lobortis, nisi nibh','/uploads/laptop.jpg',4825),
(80,'Upton','convallis est,','/uploads/laptop.jpg',4290),
(81,'Burton','sed pede. Cum sociis natoque penatibus et magnis dis','/uploads/laptop.jpg',3168),
(82,'Lionel','aliquet. Phasellus fermentum convallis ligula. Donec luctus','/uploads/laptop.jpg',1389),
(83,'Amal','Sed molestie. Sed id risus quis','/uploads/laptop.jpg',4404),
(84,'Brendan','montes, nascetur ridiculus mus. Donec dignissim magna a tortor.','/uploads/laptop.jpg',2323),
(85,'Plato','dui.','/uploads/laptop.jpg',4428),
(86,'Upton','vulputate, nisi sem semper erat,','/uploads/laptop.jpg',5653),
(87,'Hu','ligula. Nullam enim.','/uploads/laptop.jpg',3),
(88,'Drake','sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,','/uploads/laptop.jpg',204),
(89,'Driscoll','sit amet metus. Aliquam erat volutpat. Nulla facilisis.','/uploads/laptop.jpg',6673),
(90,'Jin','congue a, aliquet vel, vulputate eu, odio. Phasellus at','/uploads/laptop.jpg',3314),
(91,'Porter','accumsan sed, facilisis vitae, orci. Phasellus','/uploads/laptop.jpg',5430),
(92,'Aristotle','lorem, eget mollis lectus pede et risus. Quisque libero','/uploads/laptop.jpg',225),
(93,'Yoshio','Proin nisl sem, consequat nec, mollis vitae, posuere at,','/uploads/laptop.jpg',8191),
(94,'Ezra','rutrum, justo. Praesent luctus. Curabitur','/uploads/laptop.jpg',5422),
(95,'Hall','scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed','/uploads/laptop.jpg',346),
(96,'Conan','ut dolor dapibus gravida.','/uploads/laptop.jpg',2530),
(97,'Lester','amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.','/uploads/laptop.jpg',5892),
(98,'Daquan','sagittis. Duis','/uploads/laptop.jpg',607),
(99,'Perry','mi. Aliquam','/uploads/laptop.jpg',5525),
(100,'Asher','risus. Donec egestas.','/uploads/laptop.jpg',129);
